### ISSUE TITLE
Add media in product media section is not working

### ISSUE THREAD

**Issue by twin-elements** [aropixel/sylius-admin-media-plugin#5]
When I click Add in Product > Media, i see something like this 

![sylius-media-error](https://user-images.githubusercontent.com/17727266/91546804-548ee700-e923-11ea-83a7-03674f1e722c.jpg)

 instead artgris media type.

**Comment by GitHubExpertIT** [comment]
Hello, any news about the above issue ?

Thanks for your help

**Comment by davidroberto** [comment]
Thanks to @qdevos pull request, this is fixed!
